* Coding Lesson Contests: Promoting open-source solutions to common programming problems

** `TODO`
*** Give explanations and examples for each of the [[#scoring]] criteria
*** Complete [[#style-and-organization]] section
**** Make example submission
***** Make example repository
***** Make a bash script for submission skeleton setup
**** Fill in text of style and organization section
*** Reassess the situation and make TODOs accordingly

** Rules

*** Style and Organization

Feel free to use the bash script provided in the contest GitHub repository to make a new skeleton folder with contents in accordance with the style and organization criteria outlined below.

Submissions must follow literate programming practices as outlined below and demonstrated in the example submission located here

Submissions must be in the form of an Org-mode document, and must follow literate programming practices as outlined below and demonstrated in the included example.

*** Language

1. Prose must be in [[https://en.wikipedia.org/wiki/English_language][English]] unless otherwise specified.

2. Code must be in [[https://fsharp.org/][F#]] unless otherwise specified. If the code fails to compile, the submission will not be accepted.

*** Originality

1. Submissions may contain work by people other than the contestant, but may not include content for which the contestant does not have the right to submit under Copyright Law, and the [[#license][Licensing]] section below.
2. If a submission contains work by people other than the contestant, proper [[https://www.citationmachine.net/resources/citing-sources-apa/][attribution]] must be given. APA format isn't necessary, but can be convenient if you choose to use it.
3. Submissions may not merely repackage the work of another. They must contain original content. The amount of original content required, both in total and in relation to the quantity of the content of others, is subject to the discernment of the judge(s).

*** Submissions

1. Each contestant may make only one submission per contest.

2. In order to be considered, content (prose, code, image(s)) must arrive as a pull request to the appropriate GitHub repository before the deadline specified in the contest [[#postings][posting]], and the submission form must be filled out and submitted via Google Forms.

   Note: pull requests made prior to the deadline may be given feedback at the discretion of the judges. Contestants may use this to their advantage, if they so wish. The sumission form contains a field for the git commit hash to be considered by the judges for review. Only the commit indicated in the submission form will be judged in the context of the contest.

3. Only submissions submitted under the [[https://www.gnu.org/licenses/gpl-3.0.en.html][Gnu General Public License version 3.0]] will be accepted.

   What does this mean?
   This means that, at bare minimum, the following must be adhered to, with the exception of providing a paper mail address.

   #+BEGIN_EXAMPLE
              How to Apply These Terms to Your New Programs

    If you develop a new program, and you want it to be of the greatest
  possible use to the public, the best way to achieve this is to make it
  free software which everyone can redistribute and change under these terms.

    To do so, attach the following notices to the program.  It is safest
  to attach them to the start of each source file to most effectively
  state the exclusion of warranty; and each file should have at least
  the "copyright" line and a pointer to where the full notice is found.

      <one line to give the program's name and a brief idea of what it does.>
      Copyright (C) <year>  <name of author>

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.

      You should have received a copy of the GNU General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

  Also add information on how to contact you by electronic and paper mail.

    If the program does terminal interaction, make it output a short
  notice like this when it starts in an interactive mode:

      <program>  Copyright (C) <year>  <name of author>
      This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
      This is free software, and you are welcome to redistribute it
      under certain conditions; type `show c' for details.

  The hypothetical commands `show w' and `show c' should show the appropriate
  parts of the General Public License.  Of course, your program's commands
  might be different; for a GUI interface, you would use an "about box".

    You should also get your employer (if you work as a programmer) or school,
  if any, to sign a "copyright disclaimer" for the program, if necessary.
  For more information on this, and how to apply and follow the GNU GPL, see
  <https://www.gnu.org/licenses/>.

    The GNU General Public License does not permit incorporating your program
  into proprietary programs.  If your program is a subroutine library, you
  may consider it more useful to permit linking proprietary applications with
  the library.  If this is what you want to do, use the GNU Lesser General
  Public License instead of this License.  But first, please read
  <https://www.gnu.org/licenses/why-not-lgpl.html>.
  #+END_EXAMPLE

** Scoring

*** Code (0-50 pts) will be scored based upon the following criteria (adopted from [[https://link.springer.com/book/10.1007/978-1-4842-4000-7][Stylish F#, by Kit Eason, 2022]])

1. Motivational Transparency (0-15 pts)

2. Semantic Focus (0-15 pts)

3. Mechanical Sympathy (0-10 pts)

4. Revisability (0-10 pts)

**** The following infractions will automatically result in a zero 'Code' score.

***** Failure to test logic.

***** Failure for the code or tests to compile.

***** Failure to earn at least 50% of the possible points in any of the above Code scoring categories.

*** Prose will be scored based upon the following criteria

1. Clarity and Precision (0-10 pts)

2. Accuracy and Truthfulness (0-10 pts)

3. Economy of Expression and Neatness (0-10 pts)

4. Pleasantness and Readability (0-10 pts)

5. Organization and Formatting (0-10 pts)

**** The following infractions will automatically result in a zero 'Prose' score.

***** Failure to earn at least 50% of the possible points in any of the above Prose scoring categories.

*** Earning a zero in either Code or Prose will cause any given submission to be disqualified from competition.

** Postings

Contest postings shall include the following

1. Prompt: Title + short explanation + any additional information such as target audience, assumed prerequisite knowledge, etc..

2. Submission deadline

3. List of prizes

4. List of judges

5. Language version information, etc.

6. Link to GitHub repository + git hash of the specific version of the rules being used

7. Link to GitHub repository specific to the individual contest

8. Link to submission form (fill this out only after you have finalized your submission)

** License

#+BEGIN_EXAMPLE
Coding Lesson Contests: Promoting open-source solutions to common programming problems
    Copyright (C) 2022 Matthew I. Laine

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Contact Matt Laine
matt@brain-fuel.co
#+END_EXAMPLE
