* Coding Contests: Promoting open-source solutions to common programming problems
#+NAME:Rules
** Rules
*** Submissions
0. Submissions must be in the form of an Org-mode document, and must follow the spirit of [[Literate Programming]]
1. Code must be in F# unless otherwise specified.
2. Prose must be in English unless otherwise specified.
3. Submissions may contain work by people other than the contestant, may only include content for which the contestant has the right to submit under GPLv3.0 by Copyright Law.
4. If a submission contains work by people other than the contestant, proper attribution must be given.
5. Submissions may not merely repackage the work of another. They must contain original content.
6. Only submissions submitted under the Gnu General Public License version 3.0 will be accepted.

   What does this mean?

   This means that the following must be adhered to, with the exception of providing a paper mail address.

   #+BEGIN_EXAMPLE
              How to Apply These Terms to Your New Programs

    If you develop a new program, and you want it to be of the greatest
  possible use to the public, the best way to achieve this is to make it
  free software which everyone can redistribute and change under these terms.

    To do so, attach the following notices to the program.  It is safest
  to attach them to the start of each source file to most effectively
  state the exclusion of warranty; and each file should have at least
  the "copyright" line and a pointer to where the full notice is found.

      <one line to give the program's name and a brief idea of what it does.>
      Copyright (C) <year>  <name of author>

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU General Public License as published by
      the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.

      You should have received a copy of the GNU General Public License
      along with this program.  If not, see <https://www.gnu.org/licenses/>.

  Also add information on how to contact you by electronic and paper mail.

    If the program does terminal interaction, make it output a short
  notice like this when it starts in an interactive mode:

      <program>  Copyright (C) <year>  <name of author>
      This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
      This is free software, and you are welcome to redistribute it
      under certain conditions; type `show c' for details.

  The hypothetical commands `show w' and `show c' should show the appropriate
  parts of the General Public License.  Of course, your program's commands
  might be different; for a GUI interface, you would use an "about box".

    You should also get your employer (if you work as a programmer) or school,
  if any, to sign a "copyright disclaimer" for the program, if necessary.
  For more information on this, and how to apply and follow the GNU GPL, see
  <https://www.gnu.org/licenses/>.

    The GNU General Public License does not permit incorporating your program
  into proprietary programs.  If your program is a subroutine library, you
  may consider it more useful to permit linking proprietary applications with
  the library.  If this is what you want to do, use the GNU Lesser General
  Public License instead of this License.  But first, please read
  <https://www.gnu.org/licenses/why-not-lgpl.html>.
  #+END_EXAMPLE

** Scoring
*** Code will be scored on a scale of 1-10 based upon the following criteria (adopted from Kit Eason, 2022)
**** Semantic Focus
**** Revisability
**** Motivational Transparency
**** Mechanical Sympathy
**** Testing
***
** Literate Programming
** License
#+BEGIN_EXAMPLE
Coding Contests: Promoting open-source solutions to common programming problems
    Copyright (C) 2022  Matthew I. Laine

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

Contact Matt Laine
matt@brain-fuel.co
#+END_EXAMPLE
